In [2]:
import pandas as pd

In [3]:
# to install 
# !pip install pandas

use dataset from kaggle or other csv or excel spreadshit. here i have used built in dataset provided by seaborn module. seaborn is visualization module.

In [4]:
import seaborn as sns
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [5]:
df = sns.load_dataset('tips')
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [6]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

### key features of pandas
1. label based indexing
2. column/ row wise operation
3. support mixed data type
4. fast, verctorized operations (built on numpy)

In [7]:
import numpy as np
# Create and populate a 5x2 NumPy array.
my_data = np.array([[0, 3], [10, 7], [20, 9], [30, 14], [40, 15]])

# Create a Python list that holds the names of the two columns.
my_column_names = ['temperature', 'activity']

# Create a DataFrame.
my_dataframe = pd.DataFrame(data=my_data, columns=my_column_names)

# Print the entire DataFrame
print(my_dataframe)

   temperature  activity
0            0         3
1           10         7
2           20         9
3           30        14
4           40        15

In [8]:
# loading a data frame
# df = pd.read_csv('data.csv')
# df = pd.read_excel('data.xlsx')
# df = pd.DataFrame(data_dict)     # from dictionary

In [9]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [10]:
df.head()
df.tail()
df.sample(5)

     total_bill   tip   sex smoker   day    time  size
193       15.48  2.02  Male    Yes  Thur   Lunch     2
64        17.59  2.64  Male     No   Sat  Dinner     3
47        32.40  6.00  Male     No   Sun  Dinner     4
35        24.06  3.60  Male     No   Sat  Dinner     3
237       32.83  1.17  Male    Yes   Sat  Dinner     2

In [11]:
df.shape

(244, 7)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [13]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [14]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(1)

In [16]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [17]:
df.index

RangeIndex(start=0, stop=244, step=1)

In [18]:
pd.unique(df['day'])

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [19]:
len(df['total_bill'])

244

In [20]:
set(df['day'])

{'Fri', 'Sat', 'Sun', 'Thur'}

In [21]:
print("Rows #0, #1, and #2:")
print(df.head(3), '\n')

print("Row #2:")
print(df.iloc[[2]], '\n')

print("Rows #1, #2, and #3:")
print(df[1:4], '\n')

print("column 'day':")
print(df['day'])

Rows #0, #1, and #2:
   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

Row #2:
   total_bill  tip   sex smoker  day    time  size
2       21.01  3.5  Male     No  Sun  Dinner     3

Rows #1, #2, and #3:
   total_bill   tip   sex smoker  day    time  size
1       10.34  1.66  Male     No  Sun  Dinner     3
2       21.01  3.50  Male     No  Sun  Dinner     3
3       23.68  3.31  Male     No  Sun  Dinner     2

column 'day':
0       Sun
1       Sun
2       Sun
3       Sun
4       Sun
       ...
239     Sat
240     Sat
241     Sat
242     Sat
243    Thur
Name: day, Length: 244, dtype: category
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [22]:
pd.unique(pd.Series([("a", "b"), ("b", "a"), ("a", "c"), ("b", "a")]).values)

array([('a', 'b'), ('b', 'a'), ('a', 'c')], dtype=object)

In [23]:
df[['total_bill', 'day']]

     total_bill   day
0         16.99   Sun
1         10.34   Sun
2         21.01   Sun
3         23.68   Sun
4         24.59   Sun
..          ...   ...
239       29.03   Sat
240       27.18   Sat
241       22.67   Sat
242       17.82   Sat
243       18.78  Thur

[244 rows x 2 columns]

In [24]:
df.iloc[0]

total_bill     16.99
tip             1.01
sex           Female
smoker            No
day              Sun
time          Dinner
size               2
Name: 0, dtype: object

In [25]:
df.iloc[0]['time']

'Dinner'

In [26]:
pd.unique(df['day'])

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [27]:
df[(df["day"] == 'Thur') & (df['smoker'] == "Yes")]

     total_bill   tip     sex smoker   day   time  size
80        19.44  3.00    Male    Yes  Thur  Lunch     2
83        32.68  5.00    Male    Yes  Thur  Lunch     2
138       16.00  2.00    Male    Yes  Thur  Lunch     2
191       19.81  4.19  Female    Yes  Thur  Lunch     2
192       28.44  2.56    Male    Yes  Thur  Lunch     2
193       15.48  2.02    Male    Yes  Thur  Lunch     2
194       16.58  4.00    Male    Yes  Thur  Lunch     2
196       10.34  2.00    Male    Yes  Thur  Lunch     2
197       43.11  5.00  Female    Yes  Thur  Lunch     4
198       13.00  2.00  Female    Yes  Thur  Lunch     2
199       13.51  2.00    Male    Yes  Thur  Lunch     2
200       18.71  4.00    Male    Yes  Thur  Lunch     3
201       12.74  2.01  Female    Yes  Thur  Lunch     2
202       13.00  2.00  Female    Yes  Thur  Lunch     2
203       16.40  2.50  Female    Yes  Thur  Lunch     2
204       20.53  4.00    Male    Yes  Thur  Lunch     4
205       16.47  3.23  Female    Yes  Thur  Lunch     3

In [28]:
# df[df['CustomerName'].str.endwith('a')]

In [29]:
df[df["day"].isin(['thur', 'Fri'])]       # doesn't include because thur is lowecased where dataset has upper case Thur

     total_bill   tip     sex smoker  day    time  size
90        28.97  3.00    Male    Yes  Fri  Dinner     2
91        22.49  3.50    Male     No  Fri  Dinner     2
92         5.75  1.00  Female    Yes  Fri  Dinner     2
93        16.32  4.30  Female    Yes  Fri  Dinner     2
94        22.75  3.25  Female     No  Fri  Dinner     2
95        40.17  4.73    Male    Yes  Fri  Dinner     4
96        27.28  4.00    Male    Yes  Fri  Dinner     2
97        12.03  1.50    Male    Yes  Fri  Dinner     2
98        21.01  3.00    Male    Yes  Fri  Dinner     2
99        12.46  1.50    Male     No  Fri  Dinner     2
100       11.35  2.50  Female    Yes  Fri  Dinner     2
101       15.38  3.00  Female    Yes  Fri  Dinner     2
220       12.16  2.20    Male    Yes  Fri   Lunch     2
221       13.42  3.48  Female    Yes  Fri   Lunch     2
222        8.58  1.92    Male    Yes  Fri   Lunch     1
223       15.98  3.00  Female     No  Fri   Lunch     3
224       13.42  1.58    Male    Yes  Fri   Lunch     2
225       16.27  2.50  Female    Yes  Fri   Lunch     2
226       10.09  2.00  Female    Yes  Fri   Lunch     2

### iloc based on index loc based on label

In [30]:
df.iloc[221]

total_bill     13.42
tip             3.48
sex           Female
smoker           Yes
day              Fri
time           Lunch
size               2
Name: 221, dtype: object

In [31]:
df.loc[df['tip'] == 3.48]

     total_bill   tip     sex smoker  day    time  size
103       22.42  3.48  Female    Yes  Sat  Dinner     2
165       24.52  3.48    Male     No  Sun  Dinner     3
221       13.42  3.48  Female    Yes  Fri   Lunch     2

In [32]:
df.loc[(df['tip'] == 3.48) & (df['day'] == 'Fri')]

     total_bill   tip     sex smoker  day   time  size
221       13.42  3.48  Female    Yes  Fri  Lunch     2

### To change value

In [33]:
df.loc[(df['tip'] == 3.48) & (df['day'] == 'Fri'), 'size'] = 4
df.loc[(df['tip'] == 3.48) & (df['day'] == 'Fri')]

     total_bill   tip     sex smoker  day   time  size
221       13.42  3.48  Female    Yes  Fri  Lunch     4

In [34]:
df.iloc[221]["size"]

np.int64(4)

In [35]:
df["tip"] = df["tip"].astype(int)
df["tip"]

0      1
1      1
2      3
3      3
4      3
      ..
239    5
240    2
241    2
242    1
243    3
Name: tip, Length: 244, dtype: int64

In [38]:
df['sex'] = df['sex'].str.upper()
df['sex']

0      FEMALE
1        MALE
2        MALE
3        MALE
4      FEMALE
        ...
239      MALE
240    FEMALE
241      MALE
242      MALE
243    FEMALE
Name: sex, Length: 244, dtype: object

In [43]:
df.head()

   total_bill  tip     sex smoker  day    time  size
0       16.99    1  FEMALE     No  Sun  Dinner     2
1       10.34    1    MALE     No  Sun  Dinner     3
2       21.01    3    MALE     No  Sun  Dinner     3
3       23.68    3    MALE     No  Sun  Dinner     2
4       24.59    3  FEMALE     No  Sun  Dinner     4

In [44]:
df = df.drop(0)

In [45]:
df.head(8)

   total_bill  tip     sex smoker  day    time  size
1       10.34    1    MALE     No  Sun  Dinner     3
2       21.01    3    MALE     No  Sun  Dinner     3
3       23.68    3    MALE     No  Sun  Dinner     2
4       24.59    3  FEMALE     No  Sun  Dinner     4
6        8.77    2    MALE     No  Sun  Dinner     2
7       26.88    3    MALE     No  Sun  Dinner     4
8       15.04    1    MALE     No  Sun  Dinner     2
9       14.78    3    MALE     No  Sun  Dinner     2

### clean data

In [ ]:
df.dropna()
df.fillna({'order_id': 0}, inplace=True)

In [46]:
df.rename(columns={'sex': 'gender'}, inplace=True)

In [47]:
df.columns

Index(['total_bill', 'tip', 'gender', 'smoker', 'day', 'time', 'size'], dtype='object')

In [57]:
df = df.set_axis(['a','b','c',"d",'e','f','g'], axis=1)
df

         a  b       c    d     e       f  g
1    10.34  1    MALE   No   Sun  Dinner  3
2    21.01  3    MALE   No   Sun  Dinner  3
3    23.68  3    MALE   No   Sun  Dinner  2
4    24.59  3  FEMALE   No   Sun  Dinner  4
6     8.77  2    MALE   No   Sun  Dinner  2
..     ... ..     ...  ...   ...     ... ..
239  29.03  5    MALE   No   Sat  Dinner  3
240  27.18  2  FEMALE  Yes   Sat  Dinner  2
241  22.67  2    MALE  Yes   Sat  Dinner  2
242  17.82  1    MALE   No   Sat  Dinner  2
243  18.78  3  FEMALE   No  Thur  Dinner  2

[242 rows x 7 columns]

In [58]:
old_name = ['a','b','c',"d",'e','f','g']
new_name = ['total_bill', 'tip', 'gender', 'smoker', 'day', 'time', 'size']
df.rename(columns=dict(zip(old_name, new_name)), inplace=True)
df

     total_bill  tip  gender smoker   day    time  size
1         10.34    1    MALE     No   Sun  Dinner     3
2         21.01    3    MALE     No   Sun  Dinner     3
3         23.68    3    MALE     No   Sun  Dinner     2
4         24.59    3  FEMALE     No   Sun  Dinner     4
6          8.77    2    MALE     No   Sun  Dinner     2
..          ...  ...     ...    ...   ...     ...   ...
239       29.03    5    MALE     No   Sat  Dinner     3
240       27.18    2  FEMALE    Yes   Sat  Dinner     2
241       22.67    2    MALE    Yes   Sat  Dinner     2
242       17.82    1    MALE     No   Sat  Dinner     2
243       18.78    3  FEMALE     No  Thur  Dinner     2

[242 rows x 7 columns]

In [60]:
df['day'].value_counts()

day
Sat     87
Sun     74
Thur    62
Fri     19
Name: count, dtype: int64

In [62]:
df.groupby('day')['total_bill'].sum()

C:\Users\9849i\AppData\Local\Temp\ipykernel_6156\1987091591.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('day')['total_bill'].sum()

day
Thur    1096.33
Fri      325.88
Sat     1778.40
Sun     1584.88
Name: total_bill, dtype: float64

In [63]:
df.sort_values('total_bill', ascending=False)

     total_bill  tip  gender smoker   day    time  size
170       50.81   10    MALE    Yes   Sat  Dinner     3
212       48.33    9    MALE     No   Sat  Dinner     4
59        48.27    6    MALE     No   Sat  Dinner     4
156       48.17    5    MALE     No   Sun  Dinner     6
182       45.35    3    MALE    Yes   Sun  Dinner     3
..          ...  ...     ...    ...   ...     ...   ...
149        7.51    2    MALE     No  Thur   Lunch     2
111        7.25    1  FEMALE     No   Sat  Dinner     1
172        7.25    5    MALE    Yes   Sun  Dinner     2
92         5.75    1  FEMALE    Yes   Fri  Dinner     2
67         3.07    1  FEMALE    Yes   Sat  Dinner     1

[242 rows x 7 columns]

In [36]:
# df to csv
df.to_csv('tips_day.csv')