In [1]:
# Fetching Data from APIs: You can use Python libraries like requests to call a web API 
# (which often returns data in JSON format) and then transform that data into a pandas 
# DataFrame for analysis. This is a common method for acquiring data not stored in traditional databases.

# Creating APIs to Serve Data: By using web frameworks like FastAPI in conjunction with pandas, 
# you can quickly create a REST API that serves data directly from a pandas DataFrame, making it 
# accessible to web frontends or other services.

In [1]:
import os
from dotenv import load_dotenv

load_dotenv()

api_key = os.getenv("UR_TOKEN")

In [ ]:
import requests

url = "https://api.football-data.org/v4/competitions/PL"

headers = {
    "X-Auth-Token": api_key,
    "Accept-Encoding": ""
}

response = requests.get(url, headers=headers)

print("STATUS:", response.status_code)

STATUS: 200

In [119]:
import pandas as pd

df = pd.DataFrame(response.json()['seasons'])

In [121]:
df

,id,startDate,endDate,currentMatchday,winner
0,2403,2025-08-15,2026-05-24,22.0,None
1,2287,2024-08-16,2025-05-25,38.0,None
2,1564,2023-08-11,2024-05-19,38.0,None
3,1490,2022-08-05,2023-05-28,38.0,"{'id': 65, 'name': 'Manchester City FC', 'shor..."
4,733,2021-08-13,2022-05-22,38.0,"{'id': 65, 'name': 'Manchester City FC', 'shor..."
...,...,...,...,...,...
122,979,1892-09-01,1893-04-15,NaN,None
123,985,1891-09-03,1892-04-28,NaN,None
124,977,1890-09-04,1891-04-16,NaN,None
125,978,1889-09-05,1890-03-29,NaN,None
126,1040,1888-09-06,1889-04-18,NaN,None

In [122]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 127 entries, 0 to 126
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               127 non-null    int64
 1   startDate        127 non-null    object
 2   endDate          127 non-null    object
 3   currentMatchday  15 non-null     float64
 4   winner           33 non-null     object
dtypes: float64(1), int64(1), object(3)
memory usage: 5.1+ KB

In [123]:
dict = {'name': 'bhuwan', 'age': 23}
lsit = list(dict['name'])
lsit = ''.join(lsit)  
lsit

'bhuwan'

In [124]:
df['winner'][3]

{'id': 65,
 'name': 'Manchester City FC',
 'shortName': 'Man City',
 'tla': 'MCI',
 'crest': 'https://crests.football-data.org/65.png',
 'address': 'SportCity Manchester M11 3FF',
 'website': 'https://www.mancity.com',
 'founded': 1880,
 'clubColors': 'Sky Blue / White',
 'venue': 'Etihad Stadium',
 'lastUpdated': '2022-02-10T19:48:37Z'}

In [125]:
from collections.abc import Mapping

df['winner'] = df['winner'].apply(lambda x: x.get('name') if isinstance(x, Mapping) else None)

In [126]:
df

       id   startDate     endDate  currentMatchday              winner
0    2403  2025-08-15  2026-05-24             22.0                None
1    2287  2024-08-16  2025-05-25             38.0                None
2    1564  2023-08-11  2024-05-19             38.0                None
3    1490  2022-08-05  2023-05-28             38.0  Manchester City FC
4     733  2021-08-13  2022-05-22             38.0  Manchester City FC
..    ...         ...         ...              ...                 ...
122   979  1892-09-01  1893-04-15              NaN                None
123   985  1891-09-03  1892-04-28              NaN                None
124   977  1890-09-04  1891-04-16              NaN                None
125   978  1889-09-05  1890-03-29              NaN                None
126  1040  1888-09-06  1889-04-18              NaN                None

[127 rows x 5 columns]

In [127]:
df.sample(5)

     id   startDate     endDate  currentMatchday winner
55  912  1970-08-13  1971-05-03              NaN   None
58  915  1967-08-17  1968-05-19              NaN   None
75  940  1950-08-17  1951-05-03              NaN   None
81  928  1937-08-26  1938-05-05              NaN   None
63  922  1962-08-16  1963-05-19              NaN   None

In [128]:
df['startDate'] = pd.to_datetime(df.startDate)
df['endDate'] = pd.to_datetime(df.endDate)
df.set_index('id', inplace=True)
df

      startDate    endDate  currentMatchday              winner
id
2403 2025-08-15 2026-05-24             22.0                None
2287 2024-08-16 2025-05-25             38.0                None
1564 2023-08-11 2024-05-19             38.0                None
1490 2022-08-05 2023-05-28             38.0  Manchester City FC
733  2021-08-13 2022-05-22             38.0  Manchester City FC
...         ...        ...              ...                 ...
979  1892-09-01 1893-04-15              NaN                None
985  1891-09-03 1892-04-28              NaN                None
977  1890-09-04 1891-04-16              NaN                None
978  1889-09-05 1890-03-29              NaN                None
1040 1888-09-06 1889-04-18              NaN                None

[127 rows x 4 columns]

In [129]:
# the winner for 2024/25 was liverpul f.c and for 2023/24 was manchester city f.c
# the id doesn't make sense so remove it
# since current matchday for 2025/26 is 22 other are already finished put it 38 or drop it

In [130]:
df = df.reset_index(drop=True)
# or use 
# df.index = range(len(df))

In [131]:
df.columns

Index(['startDate', 'endDate', 'currentMatchday', 'winner'], dtype='object')

In [132]:
df.isnull().sum()

startDate            0
endDate              0
currentMatchday    112
winner              94
dtype: int64

In [133]:
df.fillna({"currentMatchday": 38}, inplace=True)

In [134]:
pd.unique(df['winner'])

array([None, 'Manchester City FC', 'Liverpool FC', 'Chelsea FC',
       'Leicester City FC', 'Manchester United FC', 'Arsenal FC',
       'Blackburn Rovers FC', 'Leeds United FC'], dtype=object)

In [135]:
df

     startDate    endDate  currentMatchday              winner
0   2025-08-15 2026-05-24             22.0                None
1   2024-08-16 2025-05-25             38.0                None
2   2023-08-11 2024-05-19             38.0                None
3   2022-08-05 2023-05-28             38.0  Manchester City FC
4   2021-08-13 2022-05-22             38.0  Manchester City FC
..         ...        ...              ...                 ...
122 1892-09-01 1893-04-15             38.0                None
123 1891-09-03 1892-04-28             38.0                None
124 1890-09-04 1891-04-16             38.0                None
125 1889-09-05 1890-03-29             38.0                None
126 1888-09-06 1889-04-18             38.0                None

[127 rows x 4 columns]

In [149]:
df.loc[df.index[2], 'winner'] = 'Manchester City FC'
df.loc[df.index[1], 'winner'] = 'Liverpool FC'

# OR
# df.iloc[2, winner_col] = 'Manchester City FC'
# df.iloc[1, winner_col] = 'Liverpool FC

In [150]:
df

     startDate    endDate  currentMatchday              winner
0   2025-08-15 2026-05-24             22.0                None
1   2024-08-16 2025-05-25             38.0        Liverpool FC
2   2023-08-11 2024-05-19             38.0  Manchester City FC
3   2022-08-05 2023-05-28             38.0  Manchester City FC
4   2021-08-13 2022-05-22             38.0  Manchester City FC
..         ...        ...              ...                 ...
122 1892-09-01 1893-04-15             38.0                None
123 1891-09-03 1892-04-28             38.0                None
124 1890-09-04 1891-04-16             38.0                None
125 1889-09-05 1890-03-29             38.0                None
126 1888-09-06 1889-04-18             38.0                None

[127 rows x 4 columns]