In [4]:
import pandas as pd
from sqlalchemy import create_engine
import sqlite3

In [2]:
# Create an engine.
engine = create_engine("sqlite:///users.db")

In [ ]:
con = sqlite3.connect('users.db')

data = pd.read_sql_query('Select * from user;', con)

In [8]:
data.describe()

              id
count  12.000000
mean    6.500000
std     3.605551
min     1.000000
25%     3.750000
50%     6.500000
75%     9.250000
max    12.000000

### Use read_sql_query() Method to Execute SQL Query

In [9]:
data

    id   username                                      password_hash
0    1        bot  scrypt:32768:8:1$K5KwJuNWgew6yDXK$56683f4fcd34...
1    2       asdf  scrypt:32768:8:1$6kobExT4qUILq2NG$001ae89fe944...
2    3     Bhuwan  scrypt:32768:8:1$VeEWJLlIfXDuDBCd$b35dd0f8a2f9...
3    4       yuki  scrypt:32768:8:1$YzScnjUdRpKLJpqj$e39fe0269313...
4    5     bhuwan  scrypt:32768:8:1$QBA6Ekm0S2Tw9Kdt$90fe29ef6a3e...
5    6  adminasdf  scrypt:32768:8:1$XO98w8fZvBvxlNbV$f6ce1d691506...
6    7        ram  scrypt:32768:8:1$0mPOfWuQGKaE4r3C$7ac1bd875eac...
7    8       subs  scrypt:32768:8:1$FlcRFQ2OI9wNTTnV$55cf2746ce3d...
8    9     subham  scrypt:32768:8:1$YbCISINU7utspU57$b9c6103d49e8...
9   10      sijan  scrypt:32768:8:1$8OCYcHTa9EyuewnH$c2ff742489b6...
10  11             scrypt:32768:8:1$82Jlp9tecAwfsLB3$91ca374078d0...
11  12    fadfads  scrypt:32768:8:1$lkSRyUvJhpPS28V3$335e8385c036...

In [11]:
data['username']

0           bot
1          asdf
2        Bhuwan
3          yuki
4        bhuwan
5     adminasdf
6           ram
7          subs
8        subham
9         sijan
10
11      fadfads
Name: username, dtype: object

### Use to_sql() Method Write into SQL Table

In [12]:
data.rename(columns={'password_hash': "password"}, inplace=True)
data

    id   username                                           password
0    1        bot  scrypt:32768:8:1$K5KwJuNWgew6yDXK$56683f4fcd34...
1    2       asdf  scrypt:32768:8:1$6kobExT4qUILq2NG$001ae89fe944...
2    3     Bhuwan  scrypt:32768:8:1$VeEWJLlIfXDuDBCd$b35dd0f8a2f9...
3    4       yuki  scrypt:32768:8:1$YzScnjUdRpKLJpqj$e39fe0269313...
4    5     bhuwan  scrypt:32768:8:1$QBA6Ekm0S2Tw9Kdt$90fe29ef6a3e...
5    6  adminasdf  scrypt:32768:8:1$XO98w8fZvBvxlNbV$f6ce1d691506...
6    7        ram  scrypt:32768:8:1$0mPOfWuQGKaE4r3C$7ac1bd875eac...
7    8       subs  scrypt:32768:8:1$FlcRFQ2OI9wNTTnV$55cf2746ce3d...
8    9     subham  scrypt:32768:8:1$YbCISINU7utspU57$b9c6103d49e8...
9   10      sijan  scrypt:32768:8:1$8OCYcHTa9EyuewnH$c2ff742489b6...
10  11             scrypt:32768:8:1$82Jlp9tecAwfsLB3$91ca374078d0...
11  12    fadfads  scrypt:32768:8:1$lkSRyUvJhpPS28V3$335e8385c036...

In [13]:
data.to_sql('user_password', con)

12